In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from __future__ import print_function
import tensorflow as tf

开始进行tensorflow的计算的时候需要开启一个session。sesseion.run()来进行计算任务

In [37]:
sess = tf.Session()

tensorflow 的计算是基于tensor的。下面介绍tensor的两种类型

# tensor的类型

## 常数(constant)

In [18]:
hello = tf.constant('Hello, TensorFlow!')
scalar1 = tf.constant(0)
matrix1 = tf.constant([[1, 1]])
matrix2 = tf.constant([[2],[2]])
matrix3 = tf.constant(1.0, shape=[2, 3])


In [20]:
print('string:\n',sess.run(hello))
print('scalar1:\n',sess.run(scalar1))
print('matrix1:\n',sess.run(matrix1))
print('matrix2:\n',sess.run(matrix2))
print('matrix3:\n',sess.run(matrix3))

string:
 b'Hello, TensorFlow!'
scalar1:
 0
matrix1:
 [[1 1]]
matrix2:
 [[2]
 [2]]
matrix3:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]


其它的常量tensor有 

* tf.zeros(shape, dtype=tf.float32, name=None) 
* tf.zeros_like(tensor, dtype=None, name=None, optimize=True)：
    * 用来产生和tensor 的shape相同的全零tensor
* tf.ones(shape, dtype=tf.float32, name=None) 
* tf.ones_like(tensor, dtype=None, name=None, optimize=True)： 
    * 用来产生和tensor 的shape相同的全一tensor

### 序列

In [24]:
seq1 = tf.linspace(0.0,1.0,5)
seq2 = tf.range(0,10)
print('seq 1:\n',sess.run(seq1))
print('seq 2:\n',sess.run(seq2))

seq 1:
 [ 0.    0.25  0.5   0.75  1.  ]
seq 2:
 [0 1 2 3 4 5 6 7 8 9]


### 随机数

In [27]:
# 产生 shape [2, 3] 的tensor，tensor里面的数是服从正态分布随机数, 均值为0，方差为1
norm = tf.random_normal([2, 3], mean=0, stddev=1)

# 顺着第一维打乱tensor
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)

# 输出norm和shuff
print('First run: \n',sess.run(norm))
print('Second run: \n',sess.run(norm))
print('Orignal value:\n',sess.run(c))
print('After shuffle:\n',sess.run(shuff))

First run: 
 [[ 2.13112187  1.03375471  0.18747409]
 [-1.31574845 -0.247675   -0.36277783]]
Second run: 
 [[-1.09392798 -0.28958207 -0.78737879]
 [-0.58714288 -1.33110166 -0.98740894]]
Orignal value:
 [[1 2]
 [3 4]
 [5 6]]
After shuffle:
 [[3 4]
 [1 2]
 [5 6]]


## 变量
在通过tensorflow建模型的时候。首先要定义一个计算图，计算图的基础就是变量，变量也是一个tensor，在模型优化过程中，变量的值会发生变化。这点和常数不一样。常数是不变的。我们可以用assign来对变量进行更新。tensorflow中的Variable是一个类（Class），里面定义了各种方法。所以使用变量的流程是
* 定义变量
* 定义变量之间的计算（如用tensorflow现成的函数或者Variable类自带的函数来对变量定义更新操作）
* 定义变量的初始化操作
* 在session进行计算

In [32]:
orign_value = tf.Variable(0, name='counter')
print('Value 的name是：', orign_value.name)
one = tf.constant(1)

#三种种更新变量方式
new_value = tf.add(orign_value, one)
update_1 = tf.assign(orign_value, new_value)

update_2 = orign_value.assign(orign_value + one)

update_3 = orign_value.assign_add(one)

#初始化操作
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print('第一种')
    for _ in range(3):
        sess.run(update_1)
        print(sess.run(orign_value))
    print('第二种')
    for _ in range(3):
        sess.run(update_3)
        print(sess.run(orign_value))
    print('第三种')
    for _ in range(3):
        sess.run(update_3)
        print(sess.run(orign_value))





Value 的name是： counter_4:0
第一种
1
2
3
第二种
4
5
6
第三种
7
8
9


## Placeholder
对于模型来说它需要接受外部的输入，这时就需要用到占位符（placeholder）。它是通过字典的方式将值传递给模型的。

In [34]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.mul(input1, input2)

with tf.Session() as sess:
    print(sess.run(output, feed_dict={input1: [7.], input2: [2.]}))

[ 14.]


# Tensor 的基本操作

## 基本的算数操作

In [44]:
string1 = tf.constant('12345')
scalar1 = tf.constant(2)
matrix1 = tf.constant([[1, 1]])
matrix2 = tf.constant([[2,2]])
matrix3 = tf.constant([[3],[3]])

In [38]:
res_add = tf.add(matrix1,matrix2)
print('matrix1 + matrix2 :\n',sess.run(res_add))

matrix1 + matrix2 :
 [[3 3]]


In [39]:
res_sub = tf.sub(matrix2,matrix1)
print('matrix2 - matrix1 :\n',sess.run(res_sub))

matrix2 - matrix1 :
 [[1 1]]


In [40]:
res_mul = tf.mul(matrix1,matrix2)
print('matrix2 * matrix1 :\n',sess.run(res_mul))

matrix2 * matrix1 :
 [[2 2]]


In [42]:
res_scal_mul=tf.scalar_mul(scalar1,matrix1)
print('scalar1 * matrix1 :\n',sess.run(res_scal_mul))

scalar1 * matrix1 :
 [[2 2]]


### others
它还支持：
* tf.div(x, y, name=None)
* tf.mod(x, y, name=None)：取余
* tf.cross(a, b, name=None)：叉乘
* tf.add_n(inputs, name=None)： inputs 是list of Tensor
* tf.abs(x, name=None)
* tf.neg(x, name=None)： 取反
* tf.sign(x, name=None)： 符号函数值
* tf.inv(x, name=None)： 倒数
* tf.square(x, name=None)
* tf.round(x, name=None)
* 各种矩阵操作
* 虚数操作
* 傅立叶变换（Fourier Transform）
* 累加， 累乘
* ...


## Tensor的变换操作

### 强制转换

In [45]:
s2n = tf.string_to_number(string1)
#可以制定输出的格式，默认为浮点型（tf.float32）
s2n_int = tf.string_to_number(string1,tf.int32)
print(sess.run(s2n))
print(sess.run(s2n_int))

12345.0
12345


In [47]:
cast1 = tf.cast(matrix1, tf.float32)
print(sess.run(cast1))

[[ 1.  1.]]


#### others
* tf.to_double(x, name='ToDouble')
* tf.to_float(x, name='ToFloat')
* tf.to_int32(x, name='ToInt32')
* tf.to_int64(x, name='ToInt64')

### Tensor 的 shape，切片等操作

In [51]:
#tf.slice(input_, begin, size, name=None)
#begin 表示的是开始元素的坐标，size 每一维表示从该维取几个
input=tf.constant([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
slice1 = tf.slice(input, [1, 0, 0], [1, 1, 3])
print(sess.run(slice1))
slice2 = tf.slice(input, [1, 0, 0], [1, 2, 3])
print(sess.run(slice2))
slice3 = tf.slice(input, [1, 0, 0], [2, 1, 3])
print(sess.run(slice3))

[[[7 8 9]]]
[[[ 7  8  9]
  [10 11 12]]]
[[[ 7  8  9]]

 [[13 14 15]]]


In [52]:
#tf.split(split_dim, num_split, value, name='split')
#把tensor按照某个维度平均分成几份
input = tf.random_normal([5, 30], mean=0, stddev=1)
split0,split1,split2 = tf.split(1,3,input)
print(sess.run(tf.shape(split0)))

[ 5 10]


In [53]:
#tf.pad(tensor, paddings, mode='CONSTANT', name=None)
#在tensor的周围补一些数
#tensor是需要处理的tensor，padding指明需要pad的维度，mode 还有"REFLECT"和"SYMMETRIC"
input = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])
after_pad = tf.pad(input, paddings, "CONSTANT")
print(sess.run(after_pad))

[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]]


In [56]:
#tf.concat(concat_dim, values, name='concat')
input_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
input_2 = tf.constant([[7, 8, 9], [10, 11, 12]])

concat_0 = tf.concat(0, [input_1, input_2])
concat_1 = tf.concat(1, [input_1, input_2])

print('concatnate selon dim 0:\n',sess.run(concat_0))
print('concatnate selon dim 1:\n',sess.run(concat_1))

concatnate selon dim 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
concatnate selon dim 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [58]:
#tf.pack(values, axis=0, name='pack')
#将所有的tensor合并起来,可以选择不同的维度 和numpy中的stack比较像
input_1 = tf.constant([1, 4])
input_2 = tf.constant([2, 5])
input_3 = tf.constant([3, 6])

pack_0 = tf.pack(([input_1, input_2, input_3]))
pack_1 = tf.pack(([input_1, input_2, input_3]), axis=1)

print('pack selon dimension 0:\n', sess.run(pack_0))
print('pack selon dimension 1:\n', sess.run(pack_1))

pack selon dimension 0:
 [[1 4]
 [2 5]
 [3 6]]
pack selon dimension 1:
 [[1 2 3]
 [4 5 6]]


### Others
* tf.shape(input, name=None, out_type=tf.int32)
* tf.shape_n(input, out_type=None, name=None)
* tf.size(input, name=None, out_type=tf.int32)
* tf.rank(input, name=None)： 和矩阵的rank不同，这里指的是坐标由几个数来表示
* tf.reshape(tensor, shape, name=None)
* tf.unpack(value, num=None, axis=0, name='unpack')
* tf.reverse(tensor, dims, name=None)
* tf.extract_image_patches(images, ksizes, strides, rates, padding, name=None)
* ...